### ISSUE TITLE
Auto calibration on flats is causing kstars to abort

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#424] opened 2017-11-19 05:29 UTC
I am running Ubuntu Mate on a Raspberry Pi 3 with a QSI 583 main camera.
I have flats set to calibrate at 40,000 with 4,000 leeway.
It runs through the calibration without any obvious issues and then takes the first flat, downloading it successfully. It then aborts with a segmentation fault.
It is giving some messages about an audio file but I have no idea why.
If I turn off the calibration and manually set the time it works fine.
![screen sharing picture 19 november 2017 at 3 56 14 pm aedt](https://user-images.githubusercontent.com/20377751/32987685-cdffa436-cd46-11e7-95c4-3cc895d762e1.png)

**Comment by knro** [comment] 2017-11-19 05:49
Not enough information there, can you run it via GDB?

**Comment by phomer60** [comment] 2017-11-19 06:02
Jasem,

Can GDB run kstars without compiling it with a -g option?

Paul

**Comment by knro** [comment] 2017-11-19 06:08
If you compiled KStars yourself, you have to enable debugging via -DCMAKE_BUILD_TYPE=Debug. If you install from PPA, there are already debug symbols.

**Comment by phomer60** [comment] 2017-11-19 06:20
Jasem,

I am installing from PPA.

When I run it I am running it I get the following.

(gdb) run
Starting program: /usr/bin/kstars 

Program received signal SIGSEGV, Segmentation fault.
0x76fd9dde in ?? () from /lib/ld-linux-armhf.so.3
(gdb) 

Is it worth continuing?

Paul

**Comment by knro** [comment] 2017-11-19 06:26
Nope.. that's a problem with GDB on Ubuntu Mate RPI3. I have the exact same setup as you so I will run it today and see if I can reproduce the crash.

**Comment by knro** [comment] 2017-11-19 15:09
I just tested the exam same settings on StellarMate and I didn't get any crash. So we probably still need a way to figure out GDB.

**Comment by knro** [comment] 2017-12-04 06:42
Closing this since it is not an INDI related issue.

**Closed by knro** 2017-12-04 06:42 UTC

**Comment by phomer60** [comment] 2017-12-07 06:27
Since this appeared to be unrelated to INDI, I investigated further and found that I needed to install the following and reboot the Raspberry Pi.

sudo apt install phonon4qt5 phonon4qt5-backend-gstreamer phonon4qt5-backend-vlc
I assume some dependencies have been added.

Regards

Paul

**Comment by phomer60** [comment] 2017-12-07 07:21
Sorry, my last email was too soon.

I hadn’t realised that after the segmentation error the Flat Duration had reset to Manual and under that setting there is no issue.

So as long as you set a target ADU it happens.

Regards

Paul
